global:
  scrape_interval: 5s
  scrape_timeout: 3s
  external_labels:
    monitor: 'shop-platform-local'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  # Add application services later, for example:
  # - job_name: gateway
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["gateway:8080"]
